[project]
name = "aws-prompt-engineering-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.54",
    "click>=8.3.0",
    "reportlab>=4.4.4",
]
