AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Parent SAM template deploying environment.yml as a nested stack

Parameters:

  IdleTime:
    Type: Number
    Default: 600
    Description: Idle time in seconds before the notebooks will auto-stop

Resources:

  WorkshopNotebookControlPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: WorkshopNotebookControlPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Resource:
              - !Sub arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:prompt/*
              - !Sub arn:aws:bedrock:*:${AWS::AccountId}:inference-profile/eu.amazon.nova-lite-v1:0
              - arn:aws:bedrock:*::foundation-model/amazon.nova-lite-v1:0
            Action:
              - bedrock:InvokeModel

  NotebookLifecycleConfig:
    Type: AWS::SageMaker::NotebookInstanceLifecycleConfig
    Properties:
      NotebookInstanceLifecycleConfigName: WorkshopConfig
      OnStart:
        - Content:
            Fn::Base64:
              Fn::Sub: |
                #!/bin/bash
                set -ex
                # Auto Stop
                IDLE_TIME=${IdleTime}
                echo "Fetching the autostop script"
                cd /home/ec2-user
                rm autostop.py | true
                wget -O autostop.py https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-notebook-instance-lifecycle-config-samples/master/scripts/auto-stop-idle/autostop.py
                chown ec2-user:ec2-user autostop.py
                PYTHON_DIR=$(source /home/ec2-user/anaconda3/bin/activate /home/ec2-user/anaconda3/envs/JupyterSystemEnv && which python)
                (crontab -l 2>/dev/null; echo "*/5 * * * * $PYTHON_DIR $PWD/autostop.py --time $IDLE_TIME --ignore-connections >> /var/log/jupyter.log") | crontab -
                crontab -l

                # Fetch tags and convert them to environment variable
                NOTEBOOK_ARN=$(jq '.ResourceArn' /opt/ml/metadata/resource-metadata.json --raw-output)
                USERNAME=$(aws sagemaker list-tags --resource-arn $NOTEBOOK_ARN  | jq -r --arg ENV_VARIABLE_NAME "Username" .'Tags[] | select(.Key == $ENV_VARIABLE_NAME).Value' --raw-output)

                echo "export USERNAME=$USERNAME" > /etc/profile.d/jupyter-env.sh
                cat /etc/profile.d/jupyter-env.sh
                systemctl --no-block restart jupyter-server.service

  Environment01:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop01
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment02:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop02
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment03:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop03
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment04:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop04
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment05:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop05
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment06:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop06
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment07:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop07
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment08:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop08
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment09:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop09
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment10:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop10
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment11:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop11
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment12:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop12
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment13:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop13
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment14:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop14
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment15:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop15
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment16:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop16
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment17:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop17
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment18:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop18
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment19:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop19
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment20:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop20
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment21:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop21
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment22:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop22
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment23:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop23
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment24:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop24
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment25:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop25
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment26:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop26
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment27:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop27
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment28:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop28
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment29:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop29
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

  Environment30:
    Type: AWS::Serverless::Application
    Properties:
      Location: environment.yml
      Parameters:
        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
        Username: workshop30
        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy

#  Environment31:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop31
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment32:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop32
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment33:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop33
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment34:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop34
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment35:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop35
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment36:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop36
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment37:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop37
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment38:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop38
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment39:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop39
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment40:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop40
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment41:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop41
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment42:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop42
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment43:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop43
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment44:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop44
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment45:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop45
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment46:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop46
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment47:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop47
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment48:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop48
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment49:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop49
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
#
#  Environment50:
#    Type: AWS::Serverless::Application
#    Properties:
#      Location: environment.yml
#      Parameters:
#        NotebookLifecycleConfig: !GetAtt NotebookLifecycleConfig.NotebookInstanceLifecycleConfigName
#        Username: workshop50
#        ManagedPolicyArn: !Ref WorkshopNotebookControlPolicy
