name: Pull Request
on:
  pull_request:
    branches: ['**']

jobs:
  CfnGuard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: grolston/guard-action@main
        with:
          data_directory: './'
          rule_set: cis-aws-benchmark-level-2
          show_summary: all
          output_format: single-line-summary

  PreCommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
